[package]
name = "arbitrum-rust-colearning-cn_yangss"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.3.0", features = ["full"] }
ethers = "2.0.14"
eyre = "0.6.12"
tokio = { version = "1.49.0", features = ["full"] }
